import { gsap ,TimelineLite,Power3} from 'gsap/dist/gsap';
import Projects from "./contentPages/projects"
import Experience from "./contentPages/experience"
import TrainingSkills from './contentPages/trainingSkills';
import Contact from "./contentPages/contact";
import Link from "next/link";
import lottie from "lottie-web";
import Head from "next/head";
import React ,{useEffect,useRef} from "react"
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import styles from "../styles/Home.module.css";

gsap.registerPlugin(ScrollTrigger)

export async function getStaticProps() {
	const res = await fetch(`https://api.rss2json.com/v1/api.json?rss_url=https://aminalaabidi.medium.com/feed`)
	const data = await res.json()
	
	return {
		
		props: {posts:data.items.slice(0,3)}
	  }
	}

export default function Home({posts}) {

	const spliteDate=(date)=>{
		let newesDate=[];
		newesDate=date.split(' ')
		return(newesDate[0])

}




	const contain=useRef(null)
	const hello=useRef(null)
	const separator=useRef(null)
    let t1= new TimelineLite({delay:0.3})
console.log(posts)
	useEffect(()=>{
     t1.from('.pictureBn',{y:15,opacity:0,ease:Power3.easeOut,delay:0.2},'Start')
	 t1.from('.description',{y:30,opacity:0,ease:Power3.easeOut,delay:0.15},'Start')
	 t1.from('.btn',{y:35,opacity:0,ease:Power3.easeOut,delay:0.15},'Start')
	 t1.from(".conta",{y:40,opacity:0,ease:Power3.easeOut,delay:0.20},'Start')

	    lottie.loadAnimation({
		container:contain.current,
        renderer:'svg',
		autoplay:true,
		animationData: require("./../public/cssjson/amina.json")
	   }),
	   lottie.loadAnimation({
		container:hello.current,
        renderer:'svg',
        autoplay: true,
		animationData: require("./../public/cssjson/hello.json")
	   }),
	   lottie.loadAnimation({
		container:separator.current,
        renderer:'svg',
        autoplay: true,
		animationData: require("./../public/cssjson/separator.json")
	   }),
	   gsap.from('.content-cont',{
duration:3,
y:"100",
opacity:0,
ease:'ease-in',
scrollTrigger:{
	trigger:'.content-cont'
}


	   })
		
		
	},[])

  return (
	<>
    <div className={styles.container}>

     <Head>
      <title>AminaAbidi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-amina-abidi.png" />
      </Head>

   

	 

<div className="container mt-5" id="Amina">

	<div className="row">
		<div className="col-md-12">
			<div className="row">
				<div className="col-md-12">
					<div className="row">
						<div className="col-md-6">
							<div className="hello" ref={hello}></div>
							<h2>
								,I'am Amina
							</h2>
							<p className="description">
							I am a full stack developer,having an experience of building Web app with Reactjs and some other cool libraries, tools and frameworks.
							 looking to solve real world problems. I have a passion to learn and share
							  my knowledge with others as publicly as possible.
							  </p>
							<button type="button" className="btn btn-dark">
								<Link  href="https://drive.google.com/file/d/1J9i7C6Z_Fbt9YTEXBb3pKyXVaYTES2OC/view?usp=sharing">
								
							<a style={{ textDecoration: 'none' ,color:"white"}}>
								See My Resume
								</a>
								</Link>
							</button>
						</div>
						<div className="col-md-6 mt-5">
						 <img src="/banner2.png" className="pictureBn" alt="Picture of the author" width="500px"/> 
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<br></br><br></br><br></br><br></br><br></br>
<div className="container conta ">
<div ref={separator}></div>
<h1>
                Read my last blogs in <i className="fab fa-medium"></i>edium 

				</h1>
				<p className="description">
				People read blogs to learn something new.</p>	
			
				<h4>
In my free time i write blogs in Medium,because iam passionate about IT so
 i am doing it for fun,sharpen my writing skills, and nurture my creativity</h4>


				
</div>
<div className="content-cont">






<br></br><br></br>
<p className="description" style={{textDecoration:"inline"}}>Blogs By <i className="fab fa-autoprefixer"></i>mina Abidi  </p>
<div className="container">
	<div className="row">

		<div className="col-md-12">
			<div className="row">
			{posts.map((el,key)=>(
				<div key={key} className="col-md-4">
					<a href={el.link} style={{textDecoration:"none"}} >
	<div className="blog-cards ">
		<img className="blog-imgs" 
		src={el.thumbnail} />
		<div className="text-overlay">
			<h5>{el.title}</h5>
			<p><strong><i className="fas fa-calendar-day"></i> &ensp;Pub-date :</strong> {spliteDate(el.pubDate)} </p><br></br>
			
			
			
		</div>
		
	</div>
	</a>

				</div>
				))}
			</div>
			<br></br><br></br><br></br><br></br><br></br>
			
		</div>
	</div>
</div>
</div>
<div id="projects"><Projects/></div>

<div id="experience"><Experience/></div>
<div id="trainingSkills"><TrainingSkills/></div>

<div id="contact"><Contact/></div>
    </div>
	
	</>




  );
}
