import Head from "next/head";
import styles from "../../styles/Home.module.css";


export default  function Contact() {

	
  return (
    <div className={styles.container}>
      <Head>
        <title>AminaAbidi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-amina-abidi.png" />
      </Head>

      <main>
     
      <div className="container">
	<div className="row">
	<h1>
				Reach Out to me!

				</h1>
		<div className="col-md-12">
			<div>
			
				<p>
                If you wanna get in touch, talk to me about a project collaboration or just say hi,
fill up the awesome<br></br> form below or send an email 

				</p>
				<p>
					<a className="btn btn-light btn-large" href="#"><strong>Open for opportunities: Yes</strong> </a>
				</p>
			</div>
		</div>
	</div>
	 <h4> <i className="fas fa-map-marker-alt "></i>&ensp;Tunis, Tunisia</h4>
</div>
<br></br> <br></br> 
<div className="container-fluid">
	<div className="col">
	<a href=""><i className="fab fa-facebook fa-2x" style={{color:"#4064ac"}}></i></a>&ensp;
	<a href=""><i className="fab fa-linkedin fa-2x" style={{color:"#0e72a3"}}></i></a>&ensp;
	<a href=""><i className="fab fa-twitter fa-2x"style={{color:"#1c9cea"}}></i></a>&ensp;
	<a href=""><i className="fas fa-envelope fa-2x"style={{color:"#b5001a"}}></i></a>&ensp;
	<a href=""><i className="fab fa-github  fa-2x"style={{color:"black"}}></i></a>&ensp;
	<a href=""><i className="fab fa-medium fa-2x"style={{color:"black"}}></i></a>

</div>
</div>
    



</main>





</div>

	
  );
}
