import Head from "next/head";
import copy from "copy-to-clipboard"; 
import styles from "../../styles/Home.module.css";

export default function TrainingSkills() {

  // state={
  //   copytext:""
  // }


//   const handleCopyText = (e) => {
//     this.setState(state.copytext:e.target.value);
//  } 
  return (
    <div className={styles.container}>
      <Head>
      <title>AminaAbidi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-amina-abidi.png" />
      </Head>

     


      <div className="container mt-5">
	<div className="row">
		{/* <div className="col-md-12">
			<div className="row">
				<div className="col-md-6">


        <div className="scroll">
<div className="container one">

  <div className="grid-cards">
    <div className="card">
      <img src="/gomycode.png" alt="img-1" title="card image"/>
      <div className="card-body">
        <h3 className="title-card">
        <strong>FULL STACK JS DEVELOPER - MERN STACK | Oct- 2020</strong>   
        </h3>
        <p>
        FULL-TIME WEB DEVELOPEMENT
BOOTCAMP BASED ON AN ACTIVE PEDAGOGY
        </p>
      </div>
    
    </div>
    </div>
</div>
<div className="container two">
 
  <div className="grid-cards">
    <div className="card">
      <img src="/freecodecamp.jpg" alt="img-1" title="card image"/>
      <div className="card-body">
        <h3 className="title-card">
        <strong> JavaScript Algorithms and Data Structures | June- 2021</strong>   
        </h3>
        <p>
        REPRESENTING APPROXIMATELY 300 HOURS OF COURSEWORK
        </p>
      </div>
    
    </div>
    </div>
</div>


</div>
				</div>
		
    </div>
    </div> */}
    </div>
    </div>
    <div class="col-md-12 ">

    <div class="row">
     
     <div class="col-md-6">
    





       </div>
       </div>
</div>

	<div class="row">
  
		<div class="col-md-12 ">
    

          <div className="row"><div class="containers">

          <h1>
						Training & Tools
					</h1>

<div class="card">
  <div class="card-header">
    <img src="/gomycode.png" alt="city" />
  </div>
  <div class="card-body">
    <span class="tag tag-pink">Dev</span>
    <h4>
    FULL STACK JS DEVELOPER - MERN STACK | Oct- 2020
    </h4>
    <p>
     
     FULL-TIME WEB DEVELOPEMENT
BOOTCAMP BASED ON AN ACTIVE PEDAGOGY
    </p>
 
  </div>
  </div>
  <div class="card">
  <div class="card-header">
    <img src="/freecodecamp.jpg" alt="city" />
  </div>
  <div class="card-body">
    <span class="tag tag-blue">Dev</span>
    <h4>
    JavaScript Algorithms and Data Structures | June- 2021
    </h4>
    <p>
     
    REPRESENTING APPROXIMATELY 300 HOURS OF COURSEWORK
    </p>
 
  </div>
  </div>
 
</div></div>

			<div class="row">
     
				<div class="col-md-6">
        <img src="training.gif" width="580px"></img>
				</div>
				<div class="col-md-6 mt-5">
				
					<div className=" d-flex justify-content-between flex-wrap">
          <div className="col m-3">
          <i className="fab fa-php fa-5x skill"></i>
       <p className="text-center mt-3 text-secondary"> PHP</p>
          </div>
       <div className="col m-3">
        <i className="fas fa-database fa-5x skill"></i>
        <p className="text-center mt-3 text-secondary">SQL</p>
        </div>
        <div className="col m-3">
        <i className="fab fa-js fa-5x skill"></i>
        <p className="text-center mt-3 text-secondary">JavaScript</p>
        </div>
        <div className="col m-3"><i className="fab fa-node-js fa-5x skill"></i>
        <p className="text-center mt-3 text-secondary">Nodejs</p>
        
        </div>
        <div className="col m-3"> <i className="fab fa-sass fa-5x skill"></i>
        <p className="text-center mt-3 text-secondary">SCSS</p>
        </div>
        <div className="col m-3"><i className="fab fa-css3-alt fa-5x skill"></i>
        <p className="text-center mt-3 text-secondary">CSS</p>
        </div>
        <div className="col m-3"><i className="fab fa-github fa-5x skill"></i>
        <p className="text-center mt-3 text-secondary" >Github</p>
        </div>
        <div className="col m-3"><i className="fab fa-html5 fa-5x skill"></i>
        <p className="text-center mt-3 text-secondary">Html5</p>
        </div>
        <div className="col m-3"> <i className="fab fa-git fa-5x skill"></i>
        <p className="text-center mt-3 text-secondary">Git</p>
        </div>
        <div className="col m-3"> <i className="fab fa-vuejs fa-5x skill"></i>
        <p className="text-center mt-3 text-secondary">Vue js</p>
        </div>
        <div className="col m-3"> <i className="fab fa-react fa-5x skill"></i>
        <p className="text-center mt-3 text-secondary">React js</p>
        </div>
        <div className="col m-3">
         <span className="skill"> <i class="fab fa-tumblr  fa-3x "></i><i className="fab fa-stripe-s fa-3x "></i></span>
        <p className="text-center mt-3 text-secondary">TypeScript</p>
        </div>
        <div className="col m-3">
        <i class="fab fa-gitlab fa-3x skill"></i>
        <p className="text-center mt-3 text-secondary">Gitlab</p>
        </div>
        
					</div>
          <footer class="blockquote-footer mt-3">
          PASSIONATE FULL STACK DEVELOPER WHO LOVES PRODUCT BUILDING
						</footer>
				</div>
			</div>
		</div>
	</div>
</div>
    
  );
}
